"""increase original url length to 1024

Revision ID: 378dcdaf9365
Revises: e78cd4b7a6f8
Create Date: 2026-08-31 21:53:24.478974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '378dcdaf9365'
down_revision = 'e78cd4b7a6f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('original',
               existing_type=sa.VARCHAR(length=256),
               type_=sa.String(length=1024),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('original',
               existing_type=sa.String(length=1024),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###
